DEF_CMD(PUSH ,  1, 1, {tmp = 1 - 2 * commands[cur++]; stack_push (stk, tmp * (*(int *)(commands + cur))); cur += sizeof (int);})
DEF_CMD(PUSHR,  2, 2, {stack_push (stk, R[commands[cur++]]);})
DEF_CMD(POP  ,  3, 2, {R[commands[cur++]] = stack_pop (stk);})
DEF_CMD(ADD  ,  4, 0, {tmp = stack_pop (stk) + stack_pop (stk); (fabs (tmp) <= MAX_INT) ? stack_push (stk, tmp) : (printf ("\nERROR: Stack overflow\n"), abort (), 1);})
DEF_CMD(SUB  ,  5, 0, {tmp = stack_pop (stk); tmp = stack_pop (stk) - tmp; (fabs (tmp) <= MAX_INT) ? stack_push (stk, tmp) : (printf ("\nERROR: Stack overflow\n"), abort (), 1);})
DEF_CMD(MUL  ,  6, 0, {tmp = stack_pop (stk) * stack_pop (stk); (fabs (tmp) <= MAX_INT) ? stack_push (stk, tmp) : (printf ("\nERROR: Stack overflow\n"), abort (), 1);})
DEF_CMD(DIV  ,  7, 0, {tmp = stack_pop (stk); (tmp != 0) ? stack_push (stk, stack_pop (stk) / tmp) : (printf ("\nERROR: divide by zero\n"), abort (), 1);})
DEF_CMD(INC  ,  8, 2, {tmp = R[commands[cur]]; (fabs (++tmp) < MAX_INT) ? R[commands[cur++]]++ : (printf ("\nERROR: Register overflow (max)\n"), abort (), 1);})
DEF_CMD(DEC  ,  9, 2, {tmp = R[commands[cur]]; (fabs (--tmp) < MAX_INT) ? R[commands[cur++]]-- : (printf ("\nERROR: Register overflow (min)\n"), abort (), 1);})
DEF_CMD(OUT  , 10, 0, {tmp = stack_pop (stk); stack_push (stk, tmp); printf ("\nOUT\t%d", tmp);})
DEF_CMD(IN   , 11, 0, {printf ("IN\t"); scanf ("%lld", &tmp); (fabs (tmp) <= MAX_INT) ? stack_push (stk, tmp) : (printf ("\nERROR: too big number\n"), abort (), 1);})
DEF_CMD(JMP  , 12, 3, {cur = commands[cur] - 1;})
DEF_CMD(JA   , 13, 3, {tmp = stack_pop (stk); int tmp2 = stack_pop (stk); stack_push (stk, tmp2); stack_push (stk, tmp); (tmp2 > tmp) ? cur++ : cur = commands[cur] - 1;})
DEF_CMD(JB   , 14, 3, {tmp = stack_pop (stk); int tmp2 = stack_pop (stk); stack_push (stk, tmp2); stack_push (stk, tmp); (tmp2 < tmp) ? cur++ : cur = commands[cur] - 1;})
DEF_CMD(JNA  , 15, 3, {tmp = stack_pop (stk); int tmp2 = stack_pop (stk); stack_push (stk, tmp2); stack_push (stk, tmp); (tmp2 >= tmp) ? cur++ : cur = commands[cur] - 1;})
DEF_CMD(JNB  , 16, 3, {tmp = stack_pop (stk); int tmp2 = stack_pop (stk); stack_push (stk, tmp2); stack_push (stk, tmp); (tmp2 <= tmp) ? cur++ : cur = commands[cur] - 1;})
DEF_CMD(JE   , 17, 3, {tmp = stack_pop (stk); int tmp2 = stack_pop (stk); stack_push (stk, tmp2); stack_push (stk, tmp); (tmp2 == tmp) ? cur++ : cur = commands[cur] - 1;})
DEF_CMD(JNE  , 18, 3, {tmp = stack_pop (stk); int tmp2 = stack_pop (stk); stack_push (stk, tmp2); stack_push (stk, tmp); (tmp2 != tmp) ? cur++ : cur = commands[cur] - 1;})
DEF_CMD(LABEL, 19, 4, {printf ("\nHELLO, I'M LABEL AND WHAT I'M DOING HERE?\n");})
DEF_CMD(END  , 20, 0, {cur = sz; printf ("\nEND");})
