DEF_CMD(PUSH ,  1, 1, {tmp = 1 - 2 * commands[cur++]; stack_push (stk, tmp * (*(int *)(commands + cur))); cur += sizeof (int);})
DEF_CMD(PUSHR,  2, 2, {stack_push (stk, R[commands[cur++]]);})
DEF_CMD(POP  ,  3, 2, {R[commands[cur++]] = stack_pop (stk);})
DEF_CMD(ADD  ,  4, 0, {stack_push (stk, stack_pop (stk) + stack_pop (stk));})
DEF_CMD(SUB  ,  5, 0, {tmp = stack_pop (stk); stack_push (stk, stack_pop (stk) - tmp);})
DEF_CMD(MUL  ,  6, 0, {stack_push (stk, stack_pop (stk) * stack_pop (stk));})
DEF_CMD(DIV  ,  7, 0, {tmp = stack_pop (stk); (tmp != 0) ? stack_push (stk, stack_pop (stk) / tmp) : (printf ("\nERROR: divide by zero\n"), abort (), 1);})
DEF_CMD(OUT  ,  8, 0, {tmp = stack_pop (stk); stack_push (stk, tmp); printf ("OUT\t%d\n", tmp);})
DEF_CMD(JMP  ,  9, 3, {cur = commands[cur] - 1;})
DEF_CMD(LABEL, 10, 4, {printf ("\nHELLO, I'M LABEL AND WHAT I'M DOING HERE?\n");})
